Controllers/AkunController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pertemuan1.Data;
using pertemuan1.Helper;
using pertemuan1.Models;
using pertemuan1.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace pertemuan1.Controllers
{
    public class AkunController : Controller
    {
        private readonly AppDbContext _context;
        private readonly EmailService _email;

        public AkunController(AppDbContext context, EmailService e)
        {
            _context = context;
            _email = e;
        }

        public IActionResult Daftar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DaftarAsync(User data)
        {
            int OTP = BanyakBantuan.ButaOTP();
            _email.KirimEmail(data.Email, "Konfigurasi daftar", "<h1>Berhasul mendaftar</h1>" + OTP);


            if (ModelState.IsValid)
            {
                _context.Add(data);
                _context.SaveChanges();
                await _context.SaveChangesAsync();

                //return RedirectToAction(controllerName: "Akun", actionName: "Masuk");
                return Redirect("Masuk");
            }
            return View(data);
        }

        public IActionResult Masuk()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Masuk(User data)
        {
            //var cari = _context.Tb_User.Where( // proses pencarian
            //    bebas => 
            //    bebas.Username == data.Username 
            //    &&
            //    bebas.Password == data.Password
            //    ).FirstOrDefault(); // hanya dapat 1 data

            var username = _context.Tb_User.Where(
                        bebas => 
                        bebas.Username == data.Username
                        ).FirstOrDefault();

            if (username != null)
            {
                var password = _context.Tb_User.Where(bebas => bebas.Username == data.Username && bebas.Password == data.Password)
                    .Include(bebas2 => bebas2.Roles)
                    .FirstOrDefault(); // hanya dapat 1 data


                if (password != null)
                {
                    var daftar = new List<Claim>
                    {
                        new Claim("Username", username.Username),
                        new Claim("Role", username.Roles.Name)
                    };

                    await HttpContext.SignInAsync(
                       new ClaimsPrincipal(
                           new ClaimsIdentity(daftar, "Cookie", "Username", "Role")
                           )
                       );

                    if (username.Roles.Id == "1")
                    {
                        return RedirectToAction(controllerName: "Home", actionName: "Index");
                    }else if(username.Roles.Id == "2")
                    {
                        return RedirectToAction(controllerName: "Home", actionName: "Index");
                    }

                    return RedirectToAction(controllerName: "Home", actionName: "Index");
                }
                ViewBag.pesan = "Password Anda Salah";
                return View(data);
            }
            ViewBag.pesan = "Username Anda Salah";
            return View(data);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

Controllers/LayerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using pertemuan1.Models;
using pertemuan1.Service.BlogService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using pertemuan1.Helper;

namespace pertemuan1.Controllers
{
    [Authorize]
    [Route("revo")]
    public class LayerController : Controller
    {
        private readonly IBlogService _blog;
        public LayerController(IBlogService blog)
        {
            _blog = blog;
        }
        [Route("semua")]
        public async Task<ActionResult<List<Blog>>> TampilSemuaBlog()
        {
            return View("Index", await _blog.TampilSemuaBlog());
        }

        [Route("buat")]
        public IActionResult BuatBlog()
        {
            return View();
        }

        [HttpPost]
        [Route("buat")]
        //public async Task<ActionResult<Blog>> BuatBlog(Blog data)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string username = User.GetUsername().ToString();
        //        await _blog.BlogBaru(username, data);

        //        return RedirectToAction(controllerName: "Blog", actionName: "Index");
        //    }
        //    return View(data);
        //}

        [Route("Ubah")]
        public async Task<ActionResult<Blog>> UbahBlog(string id)
        {
            return View("Ubah", await _blog.TampilkanBlogIdAsync(id));
            //return View();
        }

        [HttpPost]
        [Route("Ubah")]
        public async Task<ActionResult<Blog>> UbahBlog(Blog data)
        {
            if (ModelState.IsValid)
            {
                await _blog.UbahBlog(data);

                return Redirect("detail/" + data.Id);
            }
            return View(data);
        }
    }
}

Controllers/MobilController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using pertemuan1.Models;

namespace pertemuan1.Controllers
{
    public class MobilController : Controller
    {

        public IActionResult Index()
        {
            //var mobils = new List<Models.Mobil>();
            //IEnumerable<Mobil> mobils2 = new List<Mobil>();

            //mobils.Add(new Mobil
            //{
            //    IDRegistrasi = 1,
            //    Tipe = "Verarri",
            //    Merek = "Toyota",
            //    Varian = "Apple",
            //});

            //mobils.Add(new Mobil
            //{
            //    IDRegistrasi = 2,
            //    Tipe = "Lambo",
            //    Merek = "Honda",
            //    Varian = "Android",
            //});

            //string nama = "Yusfa Julian";

            //ViewBag.namaSaya = nama;
            //ViewBag.mobils = mobils;
            //ViewData["nama"] = "Yusfaaa";

            var banyakMobil = new Models.Mobil[]
            {
                new Models.Mobil{ id = 1, Tipe = "Sedan", Merek = "Toyota", Varian="FT86"},
                new Models.Mobil{ id = 2, Tipe = "SUV", Merek = "Toyota", Varian="RAV4"},
                new Models.Mobil{ id = 3, Tipe = "Sedan", Merek = "Honda", Varian="Accord"},
                new Models.Mobil{ id = 4, Tipe = "SUV", Merek = "Honda", Varian="CRV"},
                new Models.Mobil{ id = 5, Tipe = "Sedan", Merek = "Honda", Varian="City"},
            };

            //var cariMobil = banyakMobil.Single(x => x.IDRegistrasi == 1);
            //var cariMobil = banyakMobil.Where(x => x.Tipe == "Sedan");

            //ViewBag.cari = cariMobil;
            // ViewBag.mobils = banyakMobil;
            //var tampil = banyakMobil.Where(x => x.IDRegistrasi == 1).FirstOrDefault();
            //ViewBag.mobils = tampil;

            //NO.1
            //var tampil = banyakMobil.Where(x => x.Merek == "Honda");
            //ViewBag.mobils = tampil;

            //NO.2
            //var tampil = banyakMobil.Where(x => x.Merek == "Honda" && x.Tipe == "Sedan");
            //ViewBag.mobils = tampil;

            //NO.3
            //var tampil =banyakMobil.Where(x=> x.Merek=="Honda" && x.Varian=="City").FirstOrDefault();
            //ViewBag.mobils = tampil;

            //NO.4
            //var tampil = banyakMobil.Where(x => x.Merek == "Toyota");
            //ViewBag.mobils = tampil;

            //NO.5
            //ViewBag.mobils = banyakMobil;

            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using pertemuan1.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pertemuan1.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly AppDbContext _context;
        public UserController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var read = _context.Tb_User.ToList();
            return View(read);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pertemuan1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pertemuan1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Biodata">Biodata</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Akun" asp-action="Masuk">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - pertemuan1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAkun.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pertemuan 1</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a asp-controller="Home" asp-action="Index">Pertemuan1</a>
        </div>

        <div class="card">
            <div class="card-body register-card-body">

                @RenderBody()

            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>


</body>
</html>

Views/Shared/_LayoutIndex.cshtml
@using pertemuan1.Helper
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pertemuan 1</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Pertemuan1</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Blog" asp-action="Index">Blog</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="User" asp-action="Index">User</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Mobil" asp-action="Index">Mobil</a></li>
                    @*<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Layer" asp-action="BuatBlog">BuatBlog Layer</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Layer" asp-action="Ubah">UbahBlog Layer</a></li>*@
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Admin/Home">Area Admin</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/User/Home">Area User</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Akun" asp-action="Masuk">Login</a></li>
                    <li class="nav-item">
                        @{ string cek = User.GetUsername();
                            if (cek != "")
                            {
                                <a href="/Akun/Logout"
                                   class="bi bi-box-arrow-right nav-link px-lg-3 py-3 py-lg-4" title="Keluar" style="color:red"
                                   onclick="if (!confirm('\n\nYakin ingin keluar')){ return false; }">
                                    Keluar
                                </a>
                                <b class="px-lg-0 py-lg-0 float-xl-right" style="color:cornflowerblue">@User.GetUsername()</b>
                            }
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('assets/img/uye.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1 class="display-4">Welcome</h1>
                        <p>By : Yusfa Julian</p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/yangdulu96/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://web.facebook.com/yusfa.julian.9/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/yusfajulian/pertemuan1">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Yusfa Julian 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>